In [1]:
import pandas as pd
from racecast.models.model_1.split import  get_split
from racecast.config import REPO_ROOT


PATH = REPO_ROOT / "data" / "datasets" / "feature_matrix.parquet"

df = pd.read_parquet(path=PATH)

In [2]:
df.describe()

,year,round_number,event_date,driver_id,constructor_id,circuit_id,grid_position,quali_position,grid_penalty,quali_gap_to_pole_pct,...,driver_circuit_finish_pctile,driver_quali_pos_l5_pctile,driver_podium_rate_l5_pctile,driver_podium_rate_ewm15_pctile,driver_dnf_rate_l10_pctile,driver_career_podium_rate_pctile,team_finish_l5_pctile,team_best_finish_l5_pctile,team_podium_rate_l10_pctile,team_dnf_rate_l10_pctile
count,9731.000000,9731.0,9731,9731.000000,9731.000000,9731.000000,9731.0,9703.0,9703.0,9553.0,...,7135.000000,9404.000000,9458.000000,9458.000000,9458.000000,9638.000000,9507.000000,9507.000000,9569.000000,9569.000000
mean,2014.782551,10.319392,2015-05-02 23:34:28.030007296,742.008838,136.198952,42.647724,11.025383,10.979491,0.016078,0.022227,...,0.531114,0.524617,0.524582,0.524582,0.524582,0.524123,0.548776,0.548764,0.548648,0.548543
min,2003.000000,1.0,2003-03-09 00:00:00,646.000000,1.000000,1.000000,1.0,1.0,-8.0,0.0,...,0.047619,0.041667,0.222222,0.093750,0.041667,0.100000,0.083333,0.083333,0.100000,0.083333
25%,2009.000000,5.0,2009-08-30 12:00:00,711.000000,111.000000,23.000000,6.0,6.0,0.0,0.008135,...,0.281250,0.272727,0.354167,0.229167,0.275000,0.229167,0.300000,0.300000,0.318182,0.300000
50%,2015.000000,10.0,2015-06-07 18:00:00,746.000000,172.000000,53.000000,11.0,11.0,0.0,0.016822,...,0.531250,0.525658,0.394737,0.526316,0.525000,0.526316,0.545455,0.545455,0.400000,0.550000
75%,2021.000000,15.0,2021-06-20 00:00:00,772.000000,184.000000,62.000000,16.0,16.0,0.0,0.028082,...,0.781250,0.775000,0.761905,0.772727,0.763158,0.772727,0.800000,0.800000,0.800000,0.800000
max,2026.000000,24.0,2026-09-06 00:00:00,806.000000,203.000000,77.000000,24.0,24.0,23.0,0.455956,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,6.770621,5.831016,NaN,36.601494,64.656263,24.526283,6.13132,6.102226,1.630766,0.025208,...,0.287602,0.288136,0.236970,0.282810,0.277494,0.282266,0.287108,0.286937,0.261989,0.279733

In [3]:
df.dtypes

year                                         int64
round_number                                 Int64
event_date                          datetime64[ns]
driver_id                                    int64
driver_ref                                  object
constructor_id                               int64
team_ref                                    object
circuit_id                                   int64
circuit_ref                                 object
grid_position                                Int64
quali_position                               Int64
grid_penalty                                 Int64
quali_gap_to_pole_pct                      Float64
quali_gap_to_teammate_ms                   Float64
season_progress                            Float64
team_finish_l5                             float64
team_podium_rate_l10                       float64
team_best_finish_l5                        float64
driver_finish_l5                           float64
driver_podium_rate_l5                      float64
driver_podium_rate_ewm15                   float64
driver_dnf_rate_l10                        float64
team_dnf_rate_l10                          float64
driver_circuit_finish                      float64
driver_quali_pos_l5                        float64
driver_gain_l5                             float64
driver_career_starts                         int64
driver_career_podium_rate                  float64
podium                                        Int8
grid_position_pctile                       Float64
quali_position_pctile                      Float64
grid_penalty_pctile                        Float64
driver_finish_l5_pctile                    float64
driver_circuit_finish_pctile               float64
driver_quali_pos_l5_pctile                 float64
driver_podium_rate_l5_pctile               float64
driver_podium_rate_ewm15_pctile            float64
driver_dnf_rate_l10_pctile                 float64
driver_career_podium_rate_pctile           float64
team_finish_l5_pctile                      float64
team_best_finish_l5_pctile                 float64
team_podium_rate_l10_pctile                float64
team_dnf_rate_l10_pctile                   float64
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9731 entries, 0 to 9730
Data columns (total 43 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   year                              9731 non-null   int64
 1   round_number                      9731 non-null   Int64
 2   event_date                        9731 non-null   datetime64[ns]
 3   driver_id                         9731 non-null   int64
 4   driver_ref                        9731 non-null   object
 5   constructor_id                    9731 non-null   int64
 6   team_ref                          9731 non-null   object
 7   circuit_id                        9731 non-null   int64
 8   circuit_ref                       9731 non-null   object
 9   grid_position                     9731 non-null   Int64
 10  quali_position                    9703 non-null   Int64
 11  grid_penalty                      9703 non-null   Int64
 12  quali_gap_to_pole_pct             9553 non-null   Float64
 13  quali_gap_to_teammate_ms          9553 non-null   Float64
 14  season_progress                   9731 non-null   Float64
 15  team_finish_l5                    9507 non-null   float64
 16  team_podium_rate_l10              9569 non-null   float64
 17  team_best_finish_l5               9507 non-null   float64
 18  driver_finish_l5                  8790 non-null   float64
 19  driver_podium_rate_l5             9458 non-null   float64
 20  driver_podium_rate_ewm15          9458 non-null   float64
 21  driver_dnf_rate_l10               9458 non-null   float64
 22  team_dnf_rate_l10                 9569 non-null   float64
 23  driver_circuit_finish             7135 non-null   float64
 24  driver_quali_pos_l5               9404 non-null   float64
 25  driver_gain_l5                    9586 non-null   float64
 26  driver_career_starts              9731 non-null   int64
 27  driver_career_podium_rate         9638 non-null   float64
 28  podium                            9731 non-null   Int8
 29  grid_position_pctile              9731 non-null   Float64
 30  quali_position_pctile             9703 non-null   Float64
 31  grid_penalty_pctile               9703 non-null   Float64
 32  driver_finish_l5_pctile           8790 non-null   float64
 33  driver_circuit_finish_pctile      7135 non-null   float64
 34  driver_quali_pos_l5_pctile        9404 non-null   float64
 35  driver_podium_rate_l5_pctile      9458 non-null   float64
 36  driver_podium_rate_ewm15_pctile   9458 non-null   float64
 37  driver_dnf_rate_l10_pctile        9458 non-null   float64
 38  driver_career_podium_rate_pctile  9638 non-null   float64
 39  team_finish_l5_pctile             9507 non-null   float64
 40  team_best_finish_l5_pctile        9507 non-null   float64
 41  team_podium_rate_l10_pctile       9569 non-null   float64
 42  team_dnf_rate_l10_pctile          9569 non-null   float64
dtypes: Float64(6), Int64(4), Int8(1), datetime64[ns](1), float64(23), int64(5), object(3)
memory usage: 3.2+ MB

In [5]:
max_ver = df[df["driver_ref"] == "max_verstappen"]
max_ver
# mask = max_ver.isna().any(axis=1)
# max_ver[mask]

,year,round_number,event_date,driver_id,driver_ref,constructor_id,team_ref,circuit_id,circuit_ref,grid_position,...,driver_circuit_finish_pctile,driver_quali_pos_l5_pctile,driver_podium_rate_l5_pctile,driver_podium_rate_ewm15_pctile,driver_dnf_rate_l10_pctile,driver_career_podium_rate_pctile,team_finish_l5_pctile,team_best_finish_l5_pctile,team_podium_rate_l10_pctile,team_dnf_rate_l10_pctile
4758,2015,1,2015-03-15 05:00:00,772,max_verstappen,183,toro_rosso,59,albert_park,11,...,NaN,NaN,NaN,NaN,NaN,NaN,0.777778,0.777778,0.333333,0.555556
4771,2015,2,2015-03-29 07:00:00,772,max_verstappen,183,toro_rosso,60,sepang,6,...,NaN,NaN,NaN,NaN,NaN,0.210526,0.777778,0.777778,0.333333,0.388889
4797,2015,3,2015-04-12 06:00:00,772,max_verstappen,183,toro_rosso,62,shanghai,13,...,NaN,NaN,NaN,NaN,NaN,0.225000,0.777778,0.777778,0.333333,0.388889
4819,2015,4,2015-04-19 15:00:00,772,max_verstappen,183,toro_rosso,61,bahrain,15,...,NaN,0.500000,0.394737,0.210526,0.921053,0.225000,0.777778,0.777778,0.333333,0.333333
4830,2015,5,2015-05-10 12:00:00,772,max_verstappen,183,toro_rosso,56,catalunya,6,...,NaN,0.525000,0.375000,0.225000,1.000000,0.225000,0.800000,0.800000,0.350000,0.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9627,2026,9,2026-07-05 00:00:00,772,max_verstappen,181,red_bull,1,silverstone,7,...,0.156250,0.181818,0.863636,1.000000,0.590909,1.000000,0.136364,0.272727,0.772727,0.590909
9644,2026,10,2026-07-19 00:00:00,772,max_verstappen,181,red_bull,5,spa,2,...,0.119048,0.181818,0.863636,1.000000,0.613636,1.000000,0.272727,0.272727,0.772727,0.545455
9668,2026,11,2026-07-26 00:00:00,772,max_verstappen,181,red_bull,52,hungaroring,4,...,0.200000,0.181818,0.840909,1.000000,0.590909,1.000000,0.363636,0.272727,0.818182,0.545455
9693,2026,12,2026-08-23 00:00:00,772,max_verstappen,181,red_bull,11,zandvoort,7,...,0.047619,0.272727,0.954545,1.000000,0.613636,1.000000,0.363636,0.272727,0.818182,0.545455
9713,2026,13,2026-09-06 00:00:00,772,max_verstappen,181,red_bull,7,monza,5,...,0.047619,0.272727,0.931818,1.000000,0.659091,1.000000,0.363636,0.363636,0.772727,0.545455

In [6]:
print(df["year"].min(), df["year"].max())
print(df.groupby("year").size())

2003 2026
year
2003    320
2004    360
2005    376
2006    396
2007    374
2008    368
2009    340
2010    456
2011    454
2012    478
2013    418
2014    407
2015    378
2016    462
2017    400
2018    420
2019    420
2020    340
2021    440
2022    440
2023    440
2024    479
2025    479
2026    286
dtype: int64

In [7]:
train, val, test = get_split()

In [8]:
train.head()

,year,round_number,event_date,driver_id,driver_ref,constructor_id,team_ref,circuit_id,circuit_ref,grid_position,...,driver_circuit_finish_pctile,driver_quali_pos_l5_pctile,driver_podium_rate_l5_pctile,driver_podium_rate_ewm15_pctile,driver_dnf_rate_l10_pctile,driver_career_podium_rate_pctile,team_finish_l5_pctile,team_best_finish_l5_pctile,team_podium_rate_l10_pctile,team_dnf_rate_l10_pctile
0,2003,1,2003-03-09,646,michael_schumacher,6,ferrari,59,albert_park,1,...,0.071429,NaN,0.96875,1.0000,0.09375,1.0000,0.1,0.1,1.00,0.10
1,2003,1,2003-03-09,656,barrichello,6,ferrari,59,albert_park,2,...,0.285714,NaN,0.96875,0.9375,0.21875,0.8125,0.1,0.1,1.00,0.10
2,2003,1,2003-03-09,705,montoya,134,williams,59,albert_park,3,...,0.178571,NaN,0.78125,0.8125,0.46875,0.8750,0.4,0.2,0.80,0.25
3,2003,1,2003-03-09,665,frentzen,172,sauber,59,albert_park,4,...,0.607143,NaN,0.34375,0.6250,0.65625,0.6250,0.7,0.8,0.35,0.25
4,2003,1,2003-03-09,667,panis,180,toyota,59,albert_park,5,...,0.785714,NaN,0.34375,0.3750,0.46875,0.4375,0.9,0.9,0.35,0.80

In [9]:
val.head()

,year,round_number,event_date,driver_id,driver_ref,constructor_id,team_ref,circuit_id,circuit_ref,grid_position,...,driver_circuit_finish_pctile,driver_quali_pos_l5_pctile,driver_podium_rate_l5_pctile,driver_podium_rate_ewm15_pctile,driver_dnf_rate_l10_pctile,driver_career_podium_rate_pctile,team_finish_l5_pctile,team_best_finish_l5_pctile,team_podium_rate_l10_pctile,team_dnf_rate_l10_pctile
7607,2022,1,2022-03-20,784,leclerc,6,ferrari,61,bahrain,1,...,0.578947,0.447368,0.342105,0.684211,0.105263,0.789474,0.3,0.3,0.8,0.1
7608,2022,1,2022-03-20,772,max_verstappen,181,red_bull,61,bahrain,2,...,0.105263,0.105263,0.973684,0.947368,0.421053,0.947368,0.2,0.2,0.9,0.5
7609,2022,1,2022-03-20,770,sainz,6,ferrari,61,bahrain,3,...,0.157895,0.447368,0.763158,0.789474,0.105263,0.526316,0.3,0.3,0.8,0.1
7610,2022,1,2022-03-20,753,perez,181,red_bull,61,bahrain,4,...,0.578947,0.210526,0.763158,0.842105,0.421053,0.631579,0.2,0.2,0.9,0.5
7611,2022,1,2022-03-20,736,hamilton,45,mercedes,61,bahrain,5,...,0.052632,0.052632,0.973684,1.000000,0.421053,1.000000,0.1,0.1,1.0,0.5

In [10]:
test.head()

,year,round_number,event_date,driver_id,driver_ref,constructor_id,team_ref,circuit_id,circuit_ref,grid_position,...,driver_circuit_finish_pctile,driver_quali_pos_l5_pctile,driver_podium_rate_l5_pctile,driver_podium_rate_ewm15_pctile,driver_dnf_rate_l10_pctile,driver_career_podium_rate_pctile,team_finish_l5_pctile,team_best_finish_l5_pctile,team_podium_rate_l10_pctile,team_dnf_rate_l10_pctile
8047,2023,1,2023-03-05,772,max_verstappen,181,red_bull,61,bahrain,1,...,0.823529,0.058824,1.000000,1.000000,0.176471,0.944444,0.1,0.1,1.0,0.10
8048,2023,1,2023-03-05,753,perez,181,red_bull,61,bahrain,2,...,0.441176,0.176471,0.882353,0.882353,0.176471,0.666667,0.1,0.1,1.0,0.10
8049,2023,1,2023-03-05,784,leclerc,6,ferrari,61,bahrain,3,...,0.117647,0.235294,0.882353,0.823529,0.176471,0.777778,0.2,0.3,0.9,0.40
8050,2023,1,2023-03-05,770,sainz,6,ferrari,61,bahrain,4,...,0.176471,0.117647,0.735294,0.764706,0.735294,0.611111,0.2,0.3,0.9,0.40
8051,2023,1,2023-03-05,704,alonso,61,aston_martin,61,bahrain,5,...,0.441176,0.470588,0.352941,0.470588,0.941176,0.833333,0.6,0.6,0.4,0.65