In [68]:
import fastf1
from racecast.cache import enable_cache

enable_cache()

In [69]:
season = 2026
round_number = 10
Q = "qualifying"
R = "race"

In [70]:
quali_session = fastf1.get_session(season, round_number, Q)
quali_session.load(laps=False, telemetry=False, weather=False, messages=False)
quali_session.results

core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 22 drivers: ['12', '3', '1', '63', '16', '44', '81', '41', '5', '6', '30', '10', '43', '27', '55', '87', '23', '31', '77', '11', '14', '18']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,,NaN,0 days 00:01:46.304000,0 days 00:01:45.142000,0 days 00:01:44.361000,NaT,,NaN,NaN
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,2.0,,NaN,0 days 00:01:45.930000,0 days 00:01:45.589000,0 days 00:01:44.678000,NaT,,NaN,NaN
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,3.0,,NaN,0 days 00:01:45.865000,0 days 00:01:45.454000,0 days 00:01:44.801000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,4.0,,NaN,0 days 00:01:46.185000,0 days 00:01:45.689000,0 days 00:01:44.869000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,5.0,,NaN,0 days 00:01:46.278000,0 days 00:01:45.397000,0 days 00:01:44.893000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,6.0,,NaN,0 days 00:01:46.124000,0 days 00:01:45.543000,0 days 00:01:44.895000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,7.0,,NaN,0 days 00:01:46.433000,0 days 00:01:45.671000,0 days 00:01:45.016000,NaT,,NaN,NaN
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,8.0,,NaN,0 days 00:01:46.191000,0 days 00:01:45.629000,0 days 00:01:45.143000,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,9.0,,NaN,0 days 00:01:46.609000,0 days 00:01:46.082000,0 days 00:01:45.628000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,10.0,,NaN,0 days 00:01:46.062000,0 days 00:01:45.823000,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,11.0,,NaN,0 days 00:01:46.501000,0 days 00:01:46.120000,NaT,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,12.0,,NaN,0 days 00:01:46.679000,0 days 00:01:46.331000,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,13.0,,NaN,0 days 00:01:46.795000,0 days 00:01:46.392000,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,14.0,,NaN,0 days 00:01:46.893000,0 days 00:01:46.671000,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,15.0,,NaN,0 days 00:01:47.080000,0 days 00:01:46.777000,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,16.0,,NaN,0 days 00:01:47.113000,0 days 00:01:46.779000,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,17.0,,NaN,0 days 00:01:47.120000,NaT,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,18.0,,NaN,0 days 00:01:47.801000,NaT,NaT,NaT,,NaN,NaN
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,19.0,,NaN,0 days 00:01:47.823000,NaT,NaT,NaT,,NaN,NaN
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,20.0,,NaN,0 days 00:01:47.971000,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,21.0,,NaN,0 days 00:01:50.002000,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,22.0,,NaN,0 days 00:01:50.177000,NaT,NaT,NaT,,NaN,NaN

In [71]:
race_session = fastf1.get_session(season, round_number, R)
race_session.load(laps=False, telemetry=False, weather=False, messages=False)
race_session.results

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 22 drivers: ['12', '16', '3', '44', '81', '6', '1', '5', '41', '43', '10', '30', '27', '87', '23', '55', '31', '77', '14', '18', '11', '63']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:24:42.479000,Finished,25.0,44.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,2.0,2,4.0,NaT,NaT,NaT,0 days 00:00:01.952000,Finished,18.0,44.0
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,3.0,3,2.0,NaT,NaT,NaT,0 days 00:00:11.586000,Finished,15.0,44.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,5.0,NaT,NaT,NaT,0 days 00:00:17.245000,Finished,12.0,44.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:18.988000,Finished,10.0,44.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,6.0,6,21.0,NaT,NaT,NaT,0 days 00:00:23.307000,Finished,8.0,44.0
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,7.0,7,13.0,NaT,NaT,NaT,0 days 00:00:24.014000,Finished,6.0,44.0
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,8.0,8,8.0,NaT,NaT,NaT,0 days 00:00:49.140000,Finished,4.0,44.0
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,9.0,9,7.0,NaT,NaT,NaT,0 days 00:00:50.406000,Finished,2.0,44.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,10.0,10,11.0,NaT,NaT,NaT,0 days 00:01:16.037000,Finished,1.0,44.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,11.0,11,10.0,NaT,NaT,NaT,0 days 00:01:16.991000,Finished,0.0,44.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,12.0,12,9.0,NaT,NaT,NaT,0 days 00:01:17.523000,Finished,0.0,44.0
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,13.0,13,12.0,NaT,NaT,NaT,0 days 00:01:18.348000,Finished,0.0,44.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,14.0,14,14.0,NaT,NaT,NaT,0 days 00:01:34.465000,Finished,0.0,44.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,15.0,15,15.0,NaT,NaT,NaT,0 days 00:01:44.684000,Finished,0.0,44.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,16.0,16,19.0,NaT,NaT,NaT,0 days 00:01:45.856000,Finished,0.0,44.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,17.0,17,16.0,NaT,NaT,NaT,0 days 00:01:50.925000,Finished,0.0,44.0
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,18.0,18,17.0,NaT,NaT,NaT,0 days 00:01:00.979000,Lapped,0.0,43.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,19.0,19,22.0,NaT,NaT,NaT,0 days 00:00:20.848000,Lapped,0.0,42.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,20.0,R,20.0,NaT,NaT,NaT,NaT,Retired,0.0,25.0
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,21.0,R,18.0,NaT,NaT,NaT,NaT,Retired,0.0,13.0
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,22.0,R,3.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0

In [72]:
quali_session.results.columns.symmetric_difference(race_session.results.columns)

Index([], dtype='object')

In [73]:
for col in race_session.results.columns:
    print(col)

DriverNumber
BroadcastName
Abbreviation
DriverId
TeamName
TeamColor
TeamId
FirstName
LastName
FullName
HeadshotUrl
CountryCode
Position
ClassifiedPosition
GridPosition
Q1
Q2
Q3
Time
Status
Points
Laps