In [1]:
import fastf1
from racecast.ingest.cache import enable_cache

enable_cache()

In [2]:
season = 2025
round_number = 6
Q = "qualifying"
R = "race"

In [3]:
quali_session = fastf1.get_session(season, round_number, Q)
quali_session.load(laps=False, telemetry=False, weather=False, messages=False)
quali_session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,1.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,2.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,27F4D2,mercedes,Kimi,Antonelli,Kimi Antonelli,...,3.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,4.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,5.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,64C4FF,williams,Carlos,Sainz,Carlos Sainz,...,6.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,7.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,8.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,B6BABD,haas,Esteban,Ocon,Esteban Ocon,...,9.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
22,22,Y TSUNODA,TSU,tsunoda,Red Bull Racing,3671C6,red_bull,Yuki,Tsunoda,Yuki Tsunoda,...,10.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6692FF,rb,Isack,Hadjar,Isack Hadjar,...,11.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,E80020,ferrari,Lewis,Hamilton,Lewis Hamilton,...,12.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,52E252,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,13.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
7,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,...,14.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Racing Bulls,6692FF,rb,Liam,Lawson,Liam Lawson,...,15.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,52E252,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,16.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,17.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,...,18.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,19.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,B6BABD,haas,Oliver,Bearman,Oliver Bearman,...,20.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN

In [10]:
race_session = fastf1.get_session(season, round_number, R)
race_session.load(laps=False, telemetry=False, weather=False, messages=False)
race_session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:23:06.801000,Finished,25.0,58.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:02.974000,Finished,18.0,58.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:15.519000,Finished,15.0,58.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,7.0,NaT,NaT,NaT,0 days 00:00:16.144000,Finished,12.0,58.0
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:51.741000,Finished,10.0,58.0
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,6.0,6,20.0,NaT,NaT,NaT,0 days 00:00:54.617000,Finished,8.0,58.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,7.0,7,12.0,NaT,NaT,NaT,0 days 00:00:04.593000,Lapped,6.0,57.0
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,8.0,8,9.0,NaT,NaT,NaT,0 days 00:00:11.816000,Lapped,4.0,57.0
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,9.0,9,10.0,NaT,NaT,NaT,0 days 00:00:12.775000,Lapped,2.0,57.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,10.0,10,14.0,NaT,NaT,NaT,0 days 00:00:29.027000,Lapped,1.0,57.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,11.0,11,13.0,NaT,NaT,NaT,0 days 00:00:29.850000,Lapped,0.0,57.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,12.0,12,15.0,NaT,NaT,NaT,0 days 00:00:56.075000,Lapped,0.0,57.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,13.0,13,8.0,NaT,NaT,NaT,0 days 00:00:57.173000,Lapped,0.0,57.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,14.0,14,16.0,NaT,NaT,NaT,0 days 00:00:08.487000,Lapped,0.0,56.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,15.0,15,21.0,NaT,NaT,NaT,0 days 00:00:36.886000,Lapped,0.0,56.0
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,16.0,16,18.0,NaT,NaT,NaT,0 days 00:00:07.850000,Lapped,0.0,55.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,17.0,R,22.0,NaT,NaT,NaT,NaT,Lapped,0.0,43.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,18.0,R,17.0,NaT,NaT,NaT,NaT,Retired,0.0,21.0
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,19.0,R,19.0,NaT,NaT,NaT,NaT,Retired,0.0,15.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,20.0,R,3.0,NaT,NaT,NaT,NaT,Retired,0.0,10.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,21.0,W,5.0,NaT,NaT,NaT,NaT,Did not start,0.0,0.0
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,22.0,W,11.0,NaT,NaT,NaT,NaT,Did not start,0.0,0.0

In [11]:
quali_session.results.columns.symmetric_difference(race_session.results.columns)

Index([], dtype='object')

In [12]:
for col in race_session.results.columns:
    print(col)

DriverNumber
BroadcastName
Abbreviation
DriverId
TeamName
TeamColor
TeamId
FirstName
LastName
FullName
HeadshotUrl
CountryCode
Position
ClassifiedPosition
GridPosition
Q1
Q2
Q3
Time
Status
Points
Laps