In [21]:
import fastf1

## Schedule

In [28]:
season = 2026

event_schedule_df_raw = fastf1.get_event_schedule(season)
event_schedule_df_raw
# event_schedule_df_raw.iloc[:1]

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,2026-02-13,Pre-Season Testing,testing,Practice 1,2026-02-11 10:00:00+03:00,2026-02-11 07:00:00,...,Practice 3,2026-02-13 10:00:00+03:00,2026-02-13 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 2 2026,2026-02-20,Pre-Season Testing,testing,Practice 1,2026-02-18 10:00:00+03:00,2026-02-18 07:00:00,...,Practice 3,2026-02-20 10:00:00+03:00,2026-02-20 07:00:00,None,NaT,NaT,None,NaT,NaT,True
2,1,Australia,Melbourne,FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX ...,2026-03-08,Australian Grand Prix,conventional,Practice 1,2026-03-06 12:30:00+11:00,2026-03-06 01:30:00,...,Practice 3,2026-03-07 12:30:00+11:00,2026-03-07 01:30:00,Qualifying,2026-03-07 16:00:00+11:00,2026-03-07 05:00:00,Race,2026-03-08 15:00:00+11:00,2026-03-08 04:00:00,True
3,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2026,2026-03-15,Chinese Grand Prix,sprint_qualifying,Practice 1,2026-03-13 11:30:00+08:00,2026-03-13 03:30:00,...,Sprint,2026-03-14 11:00:00+08:00,2026-03-14 03:00:00,Qualifying,2026-03-14 15:00:00+08:00,2026-03-14 07:00:00,Race,2026-03-15 15:00:00+08:00,2026-03-15 07:00:00,True
4,3,Japan,Suzuka,FORMULA 1 ARAMCO JAPANESE GRAND PRIX 2026,2026-03-29,Japanese Grand Prix,conventional,Practice 1,2026-03-27 11:30:00+09:00,2026-03-27 02:30:00,...,Practice 3,2026-03-28 11:30:00+09:00,2026-03-28 02:30:00,Qualifying,2026-03-28 15:00:00+09:00,2026-03-28 06:00:00,Race,2026-03-29 14:00:00+09:00,2026-03-29 05:00:00,True
5,4,United States,Miami Gardens,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2026,2026-05-03,Miami Grand Prix,sprint_qualifying,Practice 1,2026-05-01 12:00:00-04:00,2026-05-01 16:00:00,...,Sprint,2026-05-02 12:00:00-04:00,2026-05-02 16:00:00,Qualifying,2026-05-02 16:00:00-04:00,2026-05-02 20:00:00,Race,2026-05-03 13:00:00-04:00,2026-05-03 17:00:00,True
6,5,Canada,Montréal,FORMULA 1 LENOVO GRAND PRIX DU CANADA 2026,2026-05-24,Canadian Grand Prix,sprint_qualifying,Practice 1,2026-05-22 12:30:00-04:00,2026-05-22 16:30:00,...,Sprint,2026-05-23 12:00:00-04:00,2026-05-23 16:00:00,Qualifying,2026-05-23 16:00:00-04:00,2026-05-23 20:00:00,Race,2026-05-24 16:00:00-04:00,2026-05-24 20:00:00,True
7,6,Monaco,Monte Carlo,FORMULA 1 LOUIS VUITTON GRAND PRIX DE MONACO 2026,2026-06-07,Monaco Grand Prix,conventional,Practice 1,2026-06-05 13:30:00+02:00,2026-06-05 11:30:00,...,Practice 3,2026-06-06 12:30:00+02:00,2026-06-06 10:30:00,Qualifying,2026-06-06 16:00:00+02:00,2026-06-06 14:00:00,Race,2026-06-07 15:00:00+02:00,2026-06-07 13:00:00,True
8,7,Spain,Barcelona,FORMULA 1 MSC CRUISES GRAN PREMIO DE BARCELONA...,2026-06-14,Barcelona Grand Prix,conventional,Practice 1,2026-06-12 13:30:00+02:00,2026-06-12 11:30:00,...,Practice 3,2026-06-13 12:30:00+02:00,2026-06-13 10:30:00,Qualifying,2026-06-13 16:00:00+02:00,2026-06-13 14:00:00,Race,2026-06-14 15:00:00+02:00,2026-06-14 13:00:00,True
9,8,Austria,Spielberg,FORMULA 1 LENOVO AUSTRIAN GRAND PRIX 2026,2026-06-28,Austrian Grand Prix,conventional,Practice 1,2026-06-26 13:30:00+02:00,2026-06-26 11:30:00,...,Practice 3,2026-06-27 12:30:00+02:00,2026-06-27 10:30:00,Qualifying,2026-06-27 16:00:00+02:00,2026-06-27 14:00:00,Race,2026-06-28 15:00:00+02:00,2026-06-28 13:00:00,True
10,9,United Kingdom,Silverstone,FORMULA 1 PIRELLI BRITISH GRAND PRIX 2026,2026-07-05,British Grand Prix,sprint_qualifying,Practice 1,2026-07-03 12:30:00+01:00,2026-07-03 11:30:00,...,Sprint,2026-07-04 12:00:00+01:00,2026-07-04 11:00:00,Qualifying,2026-07-04 16:00:00+01:00,2026-07-04 15:00:00,Race,2026-07-05 15:00:00+01:00,2026-07-05 14:00:00,True
11,10,Belgium,Spa-Francorchamps,FORMULA 1 MOËT & CHANDON BELGIAN GRAND PRIX 2026,2026-07-19,Belgian Grand Prix,conventional,Practice 1,2026-07-17 13:30:00+02:00,2026-07-17 11:30:00,...,Practice 3,2026-07-18 12:30:00+02:00,2026-07-18 10:30:00,Qualifying,2026-07-18 16:00:00+02:00,2026-07-18 14:00:00,Race,2026-07-19 15:00:00+02:00,2026-07-19 13:00:00,True
12,11,Hungary,Budapest,FORMULA 1 AWS HUNGARIAN GRAND PRIX 2026,2026-07-26,Hungarian Grand Prix,conventional,Practice 1,2026-07-24 13:30:00+02:00,2026-07-24 11:30:00,...,Practice 3,2026-07-25 12:30:00+02:00,2026-07-25 10:30:00,Qualifying,2026-07-25 16:00:00+02:00,2026-07-25 14:00:00,Race,2026-07-26 15:00:00+02:00,2026-07-26 13:00:00,True
13,12,Netherlands,Zandvoort,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2026,2026-08-23,Dutch Grand Prix,sprint_qualifying,Practice 1,2026-08-21 12:30:00+02:00,2026-08-21 10:30:00,...,Sprint,2026-08-22 12:00:00+02:00,2026-08-22 10:00:00,Qualifying,2026-08-22 16:00:00+02:00,2026-08-22 14:00:00,Race,2026-08-23 15:00:00+02:00,2026-08-23 13:00:00,True
14,13,Italy,Monza,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2026,2026-09-06,Italian Grand Prix,conventional,Practice 1,2026-09-04 12:30:00+02:00,2026-09-04 10:30:00,...,Practice 3,2026-09-05 12:30:00+02:00,2026-09-05 10:30:00,Qualifying,2026-09-05 16:00:00+02:00,2026-09-05 14:00:00,Race,2026-09-06 15:00:00+02:00,2026-09-06 13:00:00,True
15,14,Spain,Madrid,FORMULA 1 TAG HEUER GRAN PREMIO DE ESPAÑA 2026,2026-09-13,Spanish Grand Prix,conventional,Practice 1,2026-09-11 13:30:00+02:00,2026-09-11 11:30:00,...,Practice 3,2026-09-12 12:30:00+02:00,2026-09-12 10:30:00,Qualifying,2026-09-12 16:00:00+02:00,2026-09-12 14:00:00,Race,2026-09-13 15:00:00+02:00,2026-09-13 13:00:00,True
16,15,Azerbaijan,Baku,FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ...,2026-09-26,Azerbaijan Grand Prix,conventional,Practice 1,2026-09-24 12:30:00+04:00,2026-09-24 08:30:00,...,Practice 3,2026-09-25 12:30:00+04:00,2026-09-25 08:30:00,Qualifying,2026-09-25 16:00:00+04:00,2026-09-25 12:00:00,Race,2026-09-26 15:00:00+04:00,2026-09-26 11:00:00,True
17,16,Bahrain,Kuala Lumpur,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX IN MALAY...,2026-10-04,Bahrain Grand Prix,conventional,Practice 1,2026-10-02 12:30:00+08:00,2026-10-02 04:30:00,...,Practice 3,2026-10-03 12:30:00+08:00,2026-10-03 04:30:00,Qualifying,2026-10-03 16:00:00+08:00,2026-10-03 08:00:00,Race,2026-10-04 15:00:00+08:00,2026-10-04 07:00:00,True
18,17,Singapore,Marina Bay,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,2026-10-11,Singapore Grand Prix,sprint_qualifying,Practice 1,2026-10-09 16:30:00+08:00,2026-10-09 08:30:00,...,Sprint,2026-10-10 17:00:00+08:00,2026-10-10 09:00:00,Qualifying,2026-10-10 21:00:00+08:00,2026-10-10 13:00:00,Race,2026-10-11 20:00:00+08:00,2026-10-11 12:00:00,True
19,18,United States,Austin,FORMULA 1 MSC CRUISES UNITED STATES GRAND PRIX...,2026-10-25,United States Grand Prix,conventional,Practice 1,2026-10-23 12:30:00-05:00,2026-10-23 17:30:00,...,Practice 3,2026-10-24 12:30:00-05:00,2026-10-24 17:30:00,Qualifying,2026-10-24 16:00:00-05:00,2026-10-24 21:00:00,Race,2026-10-25 15:00:00-05:00,2026-10-25 20:00:00,True
20,19,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026,2026-11-01,Mexico City Grand Prix,conventional,Practice 1,2026-10-30 12:30:00-06:00,2026-10-30 18:30:00,...,Practice 3,2026-10-31 11:30:00-06:00,2026-10-31 17:30:00,Qualifying,2026-10-31 15:00:00-06:00,2026-10-31 21:00:00,Race,2026-11-01 14:00:00-06:00,2026-11-01 20:00:00,True
21,20,Brazil,São Paulo,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,2026-11-08,São Paulo Grand Prix,conventional,Practice 1,2026-11-06 12:30:00-03:00,2026-11-06 15:30:00,...,Practice 3,2026-11-07 11:30:00-03:00,2026-11-07 14:30:00,Qualifying,2026-11-07 15:00:00-03:00,2026-11-07 18:00:00,Race,2026-11-08 14:00:00-03:00,2026-11-08 17:00:00,True
22,21,United States,Las Vegas,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026,2026-11-21,Las Vegas Grand Prix,conventional,Practice 1,2026-11-19 16:30:00-08:00,2026-11-20 00:30:00,...,Practice 3,2026-11-20 16:30:00-08:00,2026-11-21 00:30:00,Qualifying,2026-11-20 20:00:00-08:00,2026-11-21 04:00:00,Race,2026-11-21 20:00:00-08:00,2026-11-22 04:00:00,True
23,22,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026,2026-11-29,Qatar Grand Prix,conventional,Practice 1,2026-11-27 16:30:00+03:00,2026-11-27 13:30:00,...,Practice 3,2026-11-28 17:30:00+03:00,2026-11-28 14:30:00,Qualifying,2026-11-28 21:00:00+03:00,2026-11-28 18:00:00,Race,2026-11-29 19:00:00+03:00,2026-11-29 16:00:00,True
24,23,United Arab Emirates,Yas Marina,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2026-12-06,Abu Dhabi Grand Prix,conventional,Practice 1,2026-12-04 13:30:00+04:00,2026-12-04 09:30:00,...,Practice 3,2026-12-05 14:30:00+04:00,2026-12-05 10:30:00,Qualifying,2026-12-05 18:00:00+04:00,2026-12-05 14:00:00,Race,2026-12-06 17:00:00+04:00,2026-12-06 13:00:00,True

## Session

In [23]:
event_quali = fastf1.get_event(season, 2)
quali_2 = event_quali.get_qualifying()
quali_2.load(laps=False, telemetry=False, weather=False, messages=False)
quali_2.results

core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '1', '44', '16', '6', '12', '22', '23', '31', '27', '14', '18', '55', '10', '87', '7', '5', '30']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,1.0,,NaN,0 days 00:01:31.591000,0 days 00:01:31.200000,0 days 00:01:30.641000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:31.295000,0 days 00:01:31.307000,0 days 00:01:30.723000,NaT,,NaN,NaN
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,3.0,,NaN,0 days 00:01:30.983000,0 days 00:01:30.787000,0 days 00:01:30.793000,NaT,,NaN,NaN
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,4.0,,NaN,0 days 00:01:31.424000,0 days 00:01:31.142000,0 days 00:01:30.817000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,E80020,ferrari,Lewis,Hamilton,Lewis Hamilton,...,5.0,,NaN,0 days 00:01:31.690000,0 days 00:01:31.501000,0 days 00:01:30.927000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,6.0,,NaN,0 days 00:01:31.579000,0 days 00:01:31.450000,0 days 00:01:31.021000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6692FF,rb,Isack,Hadjar,Isack Hadjar,...,7.0,,NaN,0 days 00:01:31.162000,0 days 00:01:31.253000,0 days 00:01:31.079000,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,27F4D2,mercedes,Andrea Kimi,Antonelli,Andrea Kimi Antonelli,...,8.0,,NaN,0 days 00:01:31.676000,0 days 00:01:31.590000,0 days 00:01:31.103000,NaT,,NaN,NaN
22,22,Y TSUNODA,TSU,tsunoda,Racing Bulls,6692FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,9.0,,NaN,0 days 00:01:31.238000,0 days 00:01:31.260000,0 days 00:01:31.638000,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,10.0,,NaN,0 days 00:01:31.503000,0 days 00:01:31.595000,0 days 00:01:31.706000,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,B6BABD,haas,Esteban,Ocon,Esteban Ocon,...,11.0,,NaN,0 days 00:01:31.876000,0 days 00:01:31.625000,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,52E252,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,12.0,,NaN,0 days 00:01:31.921000,0 days 00:01:31.632000,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,13.0,,NaN,0 days 00:01:31.719000,0 days 00:01:31.688000,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,14.0,,NaN,0 days 00:01:31.923000,0 days 00:01:31.773000,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,64C4FF,williams,Carlos,Sainz,Carlos Sainz,...,15.0,,NaN,0 days 00:01:31.628000,0 days 00:01:31.840000,NaT,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,...,16.0,,NaN,0 days 00:01:31.992000,NaT,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,B6BABD,haas,Oliver,Bearman,Oliver Bearman,...,17.0,,NaN,0 days 00:01:32.018000,NaT,NaT,NaT,,NaN,NaN
7,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,...,18.0,,NaN,0 days 00:01:32.092000,NaT,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,52E252,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,19.0,,NaN,0 days 00:01:32.141000,NaT,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Red Bull Racing,3671C6,red_bull,Liam,Lawson,Liam Lawson,...,20.0,,NaN,0 days 00:01:32.174000,NaT,NaT,NaT,,NaN,NaN

In [24]:
event_race = fastf1.get_event(season, 2)
race_2 = event_race.get_race()
race_2.load(laps=False, telemetry=False, weather=False, messages=False)
race_2.results

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:30:55.026000,Finished,25.0,56.0
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,2.0,2,3.0,NaT,NaT,NaT,0 days 00:00:09.748000,Finished,18.0,56.0
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,3.0,3,2.0,NaT,NaT,NaT,0 days 00:00:11.097000,Finished,15.0,56.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,4.0,4,4.0,NaT,NaT,NaT,0 days 00:00:16.656000,Finished,12.0,56.0
31,31,E OCON,OCO,ocon,Haas F1 Team,B6BABD,haas,Esteban,Ocon,Esteban Ocon,...,5.0,5,11.0,NaT,NaT,NaT,0 days 00:00:49.969000,Finished,10.0,56.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,27F4D2,mercedes,Kimi,Antonelli,Kimi Antonelli,...,6.0,6,8.0,NaT,NaT,NaT,0 days 00:00:53.748000,Finished,8.0,56.0
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,7.0,7,10.0,NaT,NaT,NaT,0 days 00:00:56.321000,Finished,6.0,56.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,B6BABD,haas,Oliver,Bearman,Oliver Bearman,...,8.0,8,17.0,NaT,NaT,NaT,0 days 00:01:01.303000,Finished,4.0,56.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,9.0,9,14.0,NaT,NaT,NaT,0 days 00:01:10.204000,Finished,2.0,56.0
55,55,C SAINZ,SAI,sainz,Williams,64C4FF,williams,Carlos,Sainz,Carlos Sainz,...,10.0,10,15.0,NaT,NaT,NaT,0 days 00:01:16.387000,Finished,1.0,56.0
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6692FF,rb,Isack,Hadjar,Isack Hadjar,...,11.0,11,7.0,NaT,NaT,NaT,0 days 00:01:18.875000,Finished,0.0,56.0
30,30,L LAWSON,LAW,lawson,Red Bull Racing,3671C6,red_bull,Liam,Lawson,Liam Lawson,...,12.0,12,20.0,NaT,NaT,NaT,0 days 00:01:21.147000,Finished,0.0,56.0
7,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,...,13.0,13,18.0,NaT,NaT,NaT,0 days 00:01:28.401000,Finished,0.0,56.0
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,52E252,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,14.0,14,19.0,NaT,NaT,NaT,0 days 00:00:10.756000,Lapped,0.0,55.0
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,52E252,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,15.0,15,12.0,NaT,NaT,NaT,0 days 00:00:20.226000,Lapped,0.0,55.0
22,22,Y TSUNODA,TSU,tsunoda,Racing Bulls,6692FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,16.0,16,9.0,NaT,NaT,NaT,0 days 00:00:23.511000,Lapped,0.0,55.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,17.0,R,13.0,NaT,NaT,NaT,NaT,Retired,0.0,4.0
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,18.0,D,6.0,NaT,NaT,NaT,NaT,Disqualified,0.0,0.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,E80020,ferrari,Lewis,Hamilton,Lewis Hamilton,...,19.0,D,5.0,NaT,NaT,NaT,NaT,Disqualified,0.0,0.0
10,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,...,20.0,D,16.0,NaT,NaT,NaT,NaT,Disqualified,0.0,0.0