In [1]:
import fastf1

## Schedule

In [8]:
year = 2025

event_schedule_df_raw = fastf1.get_event_schedule(year)
event_schedule_df_raw.iloc[:1]

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2025,2025-02-28,Pre-Season Testing,testing,Practice 1,2025-02-26 10:00:00+03:00,2025-02-26 07:00:00,...,Practice 3,2025-02-28 10:00:00+03:00,2025-02-28 07:00:00,None,NaT,NaT,None,NaT,NaT,True

## Session

In [19]:
event_quali = fastf1.get_event(year, 2)
quali_2 = event_quali.get_qualifying()
quali_2.load(laps=False, telemetry=False, weather=False, messages=False)
quali_2.results

core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '1', '44', '16', '6', '12', '22', '23', '31', '27', '14', '18', '55', '10', '87', '7', '5', '30']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,1.0,,NaN,0 days 00:01:31.591000,0 days 00:01:31.200000,0 days 00:01:30.641000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:31.295000,0 days 00:01:31.307000,0 days 00:01:30.723000,NaT,,NaN,NaN
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,3.0,,NaN,0 days 00:01:30.983000,0 days 00:01:30.787000,0 days 00:01:30.793000,NaT,,NaN,NaN
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,4.0,,NaN,0 days 00:01:31.424000,0 days 00:01:31.142000,0 days 00:01:30.817000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,E80020,ferrari,Lewis,Hamilton,Lewis Hamilton,...,5.0,,NaN,0 days 00:01:31.690000,0 days 00:01:31.501000,0 days 00:01:30.927000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,6.0,,NaN,0 days 00:01:31.579000,0 days 00:01:31.450000,0 days 00:01:31.021000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6692FF,rb,Isack,Hadjar,Isack Hadjar,...,7.0,,NaN,0 days 00:01:31.162000,0 days 00:01:31.253000,0 days 00:01:31.079000,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,27F4D2,mercedes,Andrea Kimi,Antonelli,Andrea Kimi Antonelli,...,8.0,,NaN,0 days 00:01:31.676000,0 days 00:01:31.590000,0 days 00:01:31.103000,NaT,,NaN,NaN
22,22,Y TSUNODA,TSU,tsunoda,Racing Bulls,6692FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,9.0,,NaN,0 days 00:01:31.238000,0 days 00:01:31.260000,0 days 00:01:31.638000,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,10.0,,NaN,0 days 00:01:31.503000,0 days 00:01:31.595000,0 days 00:01:31.706000,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,B6BABD,haas,Esteban,Ocon,Esteban Ocon,...,11.0,,NaN,0 days 00:01:31.876000,0 days 00:01:31.625000,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,52E252,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,12.0,,NaN,0 days 00:01:31.921000,0 days 00:01:31.632000,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,13.0,,NaN,0 days 00:01:31.719000,0 days 00:01:31.688000,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,14.0,,NaN,0 days 00:01:31.923000,0 days 00:01:31.773000,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,64C4FF,williams,Carlos,Sainz,Carlos Sainz,...,15.0,,NaN,0 days 00:01:31.628000,0 days 00:01:31.840000,NaT,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,...,16.0,,NaN,0 days 00:01:31.992000,NaT,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,B6BABD,haas,Oliver,Bearman,Oliver Bearman,...,17.0,,NaN,0 days 00:01:32.018000,NaT,NaT,NaT,,NaN,NaN
7,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,...,18.0,,NaN,0 days 00:01:32.092000,NaT,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,52E252,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,19.0,,NaN,0 days 00:01:32.141000,NaT,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Red Bull Racing,3671C6,red_bull,Liam,Lawson,Liam Lawson,...,20.0,,NaN,0 days 00:01:32.174000,NaT,NaT,NaT,,NaN,NaN

In [20]:
event_quali = fastf1.get_event(year, 2)
race_2 = event_quali.get_race()
race_2.load(laps=False, telemetry=False, weather=False, messages=False)
race_2.results

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:30:55.026000,Finished,25.0,56.0
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,2.0,2,3.0,NaT,NaT,NaT,0 days 00:00:09.748000,Finished,18.0,56.0
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,3.0,3,2.0,NaT,NaT,NaT,0 days 00:00:11.097000,Finished,15.0,56.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,4.0,4,4.0,NaT,NaT,NaT,0 days 00:00:16.656000,Finished,12.0,56.0
31,31,E OCON,OCO,ocon,Haas F1 Team,B6BABD,haas,Esteban,Ocon,Esteban Ocon,...,5.0,5,11.0,NaT,NaT,NaT,0 days 00:00:49.969000,Finished,10.0,56.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,27F4D2,mercedes,Kimi,Antonelli,Kimi Antonelli,...,6.0,6,8.0,NaT,NaT,NaT,0 days 00:00:53.748000,Finished,8.0,56.0
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,7.0,7,10.0,NaT,NaT,NaT,0 days 00:00:56.321000,Finished,6.0,56.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,B6BABD,haas,Oliver,Bearman,Oliver Bearman,...,8.0,8,17.0,NaT,NaT,NaT,0 days 00:01:01.303000,Finished,4.0,56.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,9.0,9,14.0,NaT,NaT,NaT,0 days 00:01:10.204000,Finished,2.0,56.0
55,55,C SAINZ,SAI,sainz,Williams,64C4FF,williams,Carlos,Sainz,Carlos Sainz,...,10.0,10,15.0,NaT,NaT,NaT,0 days 00:01:16.387000,Finished,1.0,56.0
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6692FF,rb,Isack,Hadjar,Isack Hadjar,...,11.0,11,7.0,NaT,NaT,NaT,0 days 00:01:18.875000,Finished,0.0,56.0
30,30,L LAWSON,LAW,lawson,Red Bull Racing,3671C6,red_bull,Liam,Lawson,Liam Lawson,...,12.0,12,20.0,NaT,NaT,NaT,0 days 00:01:21.147000,Finished,0.0,56.0
7,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,...,13.0,13,18.0,NaT,NaT,NaT,0 days 00:01:28.401000,Finished,0.0,56.0
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,52E252,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,14.0,14,19.0,NaT,NaT,NaT,0 days 00:00:10.756000,Lapped,0.0,55.0
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,52E252,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,15.0,15,12.0,NaT,NaT,NaT,0 days 00:00:20.226000,Lapped,0.0,55.0
22,22,Y TSUNODA,TSU,tsunoda,Racing Bulls,6692FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,16.0,16,9.0,NaT,NaT,NaT,0 days 00:00:23.511000,Lapped,0.0,55.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,17.0,R,13.0,NaT,NaT,NaT,NaT,Retired,0.0,4.0
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,18.0,D,6.0,NaT,NaT,NaT,NaT,Disqualified,0.0,0.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,E80020,ferrari,Lewis,Hamilton,Lewis Hamilton,...,19.0,D,5.0,NaT,NaT,NaT,NaT,Disqualified,0.0,0.0
10,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,...,20.0,D,16.0,NaT,NaT,NaT,NaT,Disqualified,0.0,0.0