In [2]:
from json.decoder import NaN

import pandas as pd
from racecast.config import REPO_ROOT

PATH = REPO_ROOT / "data" / "datasets" / "feature_matrix.parquet"

df = pd.read_parquet(path=PATH)

In [4]:
df.describe()

,year,round_number,event_date,driver_id,constructor_id,circuit_id,grid_position,quali_position,grid_penalty,quali_gap_to_pole_pct,...,driver_podium_rate_l5,driver_podium_rate_ewm15,driver_dnf_rate_l10,team_dnf_rate_l10,driver_circuit_finish,driver_quali_pos_l5,driver_gain_l5,driver_career_starts,driver_career_podium_rate,podium
count,9731.000000,9731.0,9731,9731.000000,9731.000000,9731.000000,9731.0,9703.0,9703.0,9553.0,...,9458.000000,9458.000000,9458.000000,9569.000000,7135.000000,9404.000000,9586.000000,9731.000000,9638.000000,9731.0
mean,2014.782551,10.319392,2015-05-02 23:34:28.030007296,742.008838,136.198952,42.647724,11.025383,10.979491,0.016078,0.022227,...,0.146708,0.146325,0.186346,0.186838,8.250806,10.823731,0.136553,107.419484,0.133475,0.143356
min,2003.000000,1.0,2003-03-09 00:00:00,646.000000,1.000000,1.000000,1.0,1.0,-8.0,0.0,...,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-1.196873,0.000000,0.000000,0.0
25%,2009.000000,5.0,2009-08-30 12:00:00,711.000000,111.000000,23.000000,6.0,6.0,0.0,0.008135,...,0.000000,0.000000,0.100000,0.100000,5.000000,6.600000,-0.018681,31.000000,0.000000,0.0
50%,2015.000000,10.0,2015-06-07 18:00:00,746.000000,172.000000,53.000000,11.0,11.0,0.0,0.016822,...,0.000000,0.040845,0.200000,0.150000,8.000000,10.800000,0.140977,86.000000,0.047381,0.0
75%,2021.000000,15.0,2021-06-20 00:00:00,772.000000,184.000000,62.000000,16.0,16.0,0.0,0.028082,...,0.200000,0.224928,0.300000,0.250000,11.000000,14.600000,0.292044,166.000000,0.214286,0.0
max,2026.000000,24.0,2026-09-06 00:00:00,806.000000,203.000000,77.000000,24.0,24.0,23.0,0.455956,...,1.000000,1.000000,1.000000,0.875000,24.000000,23.800000,1.796347,440.000000,1.000000,1.0
std,6.770621,5.831016,NaN,36.601494,64.656263,24.526283,6.13132,6.102226,1.630766,0.025208,...,0.256009,0.207583,0.152667,0.127877,4.227560,5.223670,0.292210,89.869500,0.172561,0.350454

In [6]:
df.dtypes

year                                  int64
round_number                          Int64
event_date                   datetime64[ns]
driver_id                             int64
driver_ref                           object
constructor_id                        int64
team_ref                             object
circuit_id                            int64
circuit_ref                          object
grid_position                         Int64
quali_position                        Int64
grid_penalty                          Int64
quali_gap_to_pole_pct               Float64
quali_gap_to_teammate_ms            Float64
season_progress                     Float64
team_finish_l5                      float64
team_podium_rate_l10                float64
team_best_finish_l5                 float64
driver_finish_l5                    float64
driver_podium_rate_l5               float64
driver_podium_rate_ewm15            float64
driver_dnf_rate_l10                 float64
team_dnf_rate_l10                   float64
driver_circuit_finish               float64
driver_quali_pos_l5                 float64
driver_gain_l5                      float64
driver_career_starts                  int64
driver_career_podium_rate           float64
podium                                 Int8
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9731 entries, 0 to 9730
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       9731 non-null   int64
 1   round_number               9731 non-null   Int64
 2   event_date                 9731 non-null   datetime64[ns]
 3   driver_id                  9731 non-null   int64
 4   driver_ref                 9731 non-null   object
 5   constructor_id             9731 non-null   int64
 6   team_ref                   9731 non-null   object
 7   circuit_id                 9731 non-null   int64
 8   circuit_ref                9731 non-null   object
 9   grid_position              9731 non-null   Int64
 10  quali_position             9703 non-null   Int64
 11  grid_penalty               9703 non-null   Int64
 12  quali_gap_to_pole_pct      9553 non-null   Float64
 13  quali_gap_to_teammate_ms   9553 non-null   Float64
 14  season_progress            9731 non-null   Float64
 15  team_finish_l5             9507 non-null   float64
 16  team_podium_rate_l10       9569 non-null   float64
 17  team_best_finish_l5        9507 non-null   float64
 18  driver_finish_l5           8790 non-null   float64
 19  driver_podium_rate_l5      9458 non-null   float64
 20  driver_podium_rate_ewm15   9458 non-null   float64
 21  driver_dnf_rate_l10        9458 non-null   float64
 22  team_dnf_rate_l10          9569 non-null   float64
 23  driver_circuit_finish      7135 non-null   float64
 24  driver_quali_pos_l5        9404 non-null   float64
 25  driver_gain_l5             9586 non-null   float64
 26  driver_career_starts       9731 non-null   int64
 27  driver_career_podium_rate  9638 non-null   float64
 28  podium                     9731 non-null   Int8
dtypes: Float64(3), Int64(4), Int8(1), datetime64[ns](1), float64(12), int64(5), object(3)
memory usage: 2.2+ MB

In [15]:
max_ver = df[df["driver_ref"] == "max_verstappen"]
max_ver
# mask = max_ver.isna().any(axis=1)
# max_ver[mask]

,year,round_number,event_date,driver_id,driver_ref,constructor_id,team_ref,circuit_id,circuit_ref,grid_position,...,driver_podium_rate_l5,driver_podium_rate_ewm15,driver_dnf_rate_l10,team_dnf_rate_l10,driver_circuit_finish,driver_quali_pos_l5,driver_gain_l5,driver_career_starts,driver_career_podium_rate,podium
4758,2015,1,2015-03-15 05:00:00,772,max_verstappen,183,toro_rosso,59,albert_park,11,...,NaN,NaN,NaN,0.10,NaN,NaN,NaN,0,NaN,0
4771,2015,2,2015-03-29 07:00:00,772,max_verstappen,183,toro_rosso,60,sepang,6,...,NaN,NaN,NaN,0.10,NaN,NaN,NaN,1,0.000000,0
4797,2015,3,2015-04-12 06:00:00,772,max_verstappen,183,toro_rosso,62,shanghai,13,...,NaN,NaN,NaN,0.10,NaN,NaN,-0.154151,2,0.000000,0
4819,2015,4,2015-04-19 15:00:00,772,max_verstappen,183,toro_rosso,61,bahrain,15,...,0.0,0.000000,0.333333,0.10,NaN,10.333333,-0.211207,3,0.000000,0
4830,2015,5,2015-05-10 12:00:00,772,max_verstappen,183,toro_rosso,56,catalunya,6,...,0.0,0.000000,0.500000,0.20,NaN,11.500000,-0.211207,4,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9627,2026,9,2026-07-05 00:00:00,772,max_verstappen,181,red_bull,1,silverstone,7,...,0.4,0.555368,0.200000,0.20,2.666667,4.000000,0.229073,241,0.535270,0
9644,2026,10,2026-07-19 00:00:00,772,max_verstappen,181,red_bull,5,spa,2,...,0.4,0.530288,0.200000,0.20,3.000000,5.000000,0.195690,242,0.533058,1
9668,2026,11,2026-07-26 00:00:00,772,max_verstappen,181,red_bull,52,hungaroring,4,...,0.4,0.551500,0.200000,0.20,5.000000,4.200000,-0.078963,243,0.534979,1
9693,2026,12,2026-08-23 00:00:00,772,max_verstappen,181,red_bull,11,zandvoort,7,...,0.6,0.571754,0.200000,0.15,1.666667,5.000000,0.075459,244,0.536885,0
9713,2026,13,2026-09-06 00:00:00,772,max_verstappen,181,red_bull,7,monza,5,...,0.6,0.545934,0.200000,0.15,2.666667,5.400000,0.038538,245,0.534694,1